### ISSUE TITLE
update to node 14

### ISSUE THREAD

**Issue by Rexogamer** [Cytrus-RE/cytrus-re#361]
- new features uwu
- djs 12 requires node 12
- os.ver requires 14

**Comment by DestroyedEDGE** [comment]
we already run on node 12 and fuck djs 12

**Comment by Rexogamer** [comment]
- we need node 14 for smth in currentos (and always good to be up to date)
- why

**Comment by DestroyedEDGE** [comment]
- ok fair enough
- djs 12 broke a lot of things that would require a complete overhaul of the bot to fix

**Comment by Rexogamer** [comment]
tbh we need to overhaul a few things (the bot's workin but it needs work)

**Comment by Rexogamer** [comment]
done, will reopen if we find any major bugs
