### ISSUE TITLE
Unify commands that are similar

### ISSUE THREAD

**Issue by CommandBlock6417** [Cytrus-RE/cytrus-re#393]
Commands such as aes256ctr and deaes256ctr are quite similar and could be merged into one.

**Comment by Oxygemo** [comment]
Could this reduce filesizes?

**Comment by Oxygemo** [comment]
Yes, that's a thing we should focus on. 33mb for a bot like this. ugh

**Comment by CommandBlock6417** [comment]
> Yes, that's a thing we should focus on. 33mb for a bot like this. ugh

It could in theory but only slightly, I merged two files together and only managed to shave off around 500 bytes

**Comment by Oxygemo** [comment]
Still. If it reduces filesizes, then let's do it.

**Comment by Oxygemo** [comment]
That's what I want to do, I guess
