### ISSUE TITLE
Make a new logo that isn't copyrighted by Game Freak

### ISSUE THREAD

**Issue by Oxygemo** [Cytrus-RE/cytrus-re#395]
We're using a Pikachu logo for cytrus-re. This fucking sucks. So, let's make a new one! Also let me contribute to the drawing project pls

**Comment by Rexogamer** [comment]
What drawing project lol

**Comment by Oxygemo** [comment]
when we make it???

**Comment by Rexogamer** [comment]
the way you put it suggested there already was one but yes you will get access

**Comment by Oxygemo** [comment]
yay

**Comment by Oxygemo** [comment]
@CommandBlock6417 since you drew the TTS logo (or was it derser), you are the one who will manage this. my drawing skills are shit, rexo's probably good but mine is terrible

**Comment by CommandBlock6417** [comment]
I drew the logo. Derser thought of making the letters 3D, which I really liked.

**Comment by Oxygemo** [comment]
Oh, by any chance, where is the final image's project files? I want to make some artwork.

**Comment by CommandBlock6417** [comment]
Stop closing the issue. It won't remove references to you. We will re create it when we can.

**Comment by Oxygemo** [comment]
I'm here to piss people off and play counter strike, I don't give a fuck.
