### ISSUE TITLE
Merge events together

### ISSUE THREAD

**Issue by Oxygemo** [Cytrus-RE/cytrus-re#400]
We should do this, because we can simplify Cytrus-RE and (potentially) reduce filesizes (which is all I wanna do!). I can probably tackle this

**Comment by Oxygemo** [comment]
This will definitely brick things, but we could probably do the same thing as we did with Discord.js 12 upgrade, aka just do it and then patching things that broke.

**Comment by Rexogamer** [comment]
wonder why they were ever separated

**Comment by Oxygemo** [comment]
is it celestial or you

**Comment by Rexogamer** [comment]
celestial

@celestialcrafter exist damn you

**Comment by Oxygemo** [comment]
i think he forgot his github password
