### ISSUE TITLE
Add a Nightly/Beta branch

### ISSUE THREAD

**Issue by Midou36O** [cytrus-re/cytrus-re#527]
This should allow more modifications without having regressions on latest Cytrus-RE; Consider adding a Nightly Branch for PRs for example.

**Comment by Odyssey346** [comment]
we already have that, it's called master. @Rexogamer close this

**Comment by Rexogamer** [comment]
as I explained several times yesterday, `prod` is what's on the bot and `master` is our dev branch that I test on the testing bot
